server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heekuutable?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: heekuu03

  thymeleaf:
    prefix: classpath:/templates/
    enabled: true
    expose-request-attributes: true
    servlet:
      content-type: text/html
    encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  messages:
    encoding: UTF-8

  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
      enabled: true